/*
 * Copyright 2021 Amazon.com, Inc. or its affiliates. All rights reserved.
 *
 * AMAZON PROPRIETARY/CONFIDENTIAL
 *
 * You may not use this file except in compliance with the terms and
 * conditions set forth in the accompanying LICENSE.TXT file. This file is a
 * Modifiable File, as defined in the accompanying LICENSE.TXT file.
 *
 * THESE MATERIALS ARE PROVIDED ON AN "AS IS" BASIS. AMAZON SPECIFICALLY
 * DISCLAIMS, WITH RESPECT TO THESE MATERIALS, ALL WARRANTIES, EXPRESS,
 * IMPLIED, OR STATUTORY, INCLUDING THE IMPLIED WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE, AND NON-INFRINGEMENT.
 */

#ifndef ACE_CONFIG_H
#define ACE_CONFIG_H

#define RTOS_PACKAGE

#define ACE_BUILD_VARIANT "all"
#define ACE_PKG_GEN_UTC_TIMESTAMP 1614388533

#ifdef ACE_CONFIG_OVERRIDES
#include ACE_CONFIG_OVERRIDES
#endif

#define ACE_CLI
#define ACE_FACTORY_RESET_DEREGISTER_TIMEOUT 0
#define FFS_WIFI_RESCAN_LIMIT 0
#define ACE_FFS_PROVISIONABLE_TEST_CLI
#define FFS_MAX_DEVICE_REGISTRATION_RETRY 5
#define CONFIG_ACE_FFS_CLI_STACK_SIZE 6
#define ACE_FFS_SS_TRANSPORT
#define ACE_LOG
#define ACE_USE_HAL_FOR_RTOS
#define ACE_LOG_MAX_LOG_LENGTH 256
#define ACE_LOG_CONFIG_MIN_LVL 0
#define ACE_MAPLITE_DS_GROUP "map"
#define ACE_MAP_API_GET_LINKCODE
#define ACE_MAP_API_PREAUTH_LINKCODE
#define ACE_MAP_EVENT_SUPPORT
#define ACE_MAP
#define ACE_MAP_DISABLE_SYNC
#define ACE_MAP_3P_AVS_IDRS
#define ACE_MAP_3P_IOT_REGISTRATION_URL ""
#define ACE_MAP_3P_IOT_REGISTRATION_PATH ""
#define ACE_MAP_SS_TRANSPORT
#define ACE_WIFI_MIDDLEWARE
#define ACE_WIFI_MAX_CONFIGURED_NETWORKS 1
#define ACE_WIFI_MAX_NUM_CB 6
#define ACE_WIFI_MAX_SCAN_RESULTS 20
#define ACE_WIFI_MAX_TARGETED_SCAN_SSID_NUM 1
#define ACE_WIFI_MAX_PARTIAL_SCAN_CHANNEL_NUM 5
#define ACE_WIFI_SVC_MAX_MSG_ITEMS 20
#define ACE_WIFI_RSSI_THRESHOLD "-80 -75 -70 -65"
#define ACE_WIFI_NOISE_THRESHOLD "-55, -57, -62, -67, -72, -77, -81, -84, -87, -90, -92"
#define ACE_WIFI_MGR_TEST
#define ACE_NET_DS_GROUP "WifiCred"
#define ACE_CAPTIVE_PORTAL_HOST ""
#define ACE_CAPTIVE_PORTAL_URL ""
#define ACE_CAPTIVE_PORTAL_STR ""
#define ACE_WIFI_SVC_STACK_SIZE 4096
#define ACE_WIFI_NETMGR_STACK_SIZE 8192
#define ACE_WIFI_DIAGS_INTERVAL 300000
#define ACE_WIFI_DIAGS_HTTP_HOST ""
#define ACE_WIFI_DIAGS_HTTP_URL ""
#define ACE_WIFI_DIAGS_HTTP_STR ""
#define ACE_WIFI_DIAGS_HTTP_HOST_BACKUP ""
#define ACE_WIFI_DIAGS_HTTP_URL_BACKUP ""
#define ACE_WIFI_DIAGS_HTTP_STR_BACKUP ""
#define ACE_WIFI_FFS_MAX_PROVISIONEES 8
#define ACE_WIFI_METRICS_MAX_TXOP 10
#define ACE_WIFI_PING
#define ACE_WIFI_BLACKLIST_MAX_FAILURE_COUNT 3
#define ACE_WIFI_BLACKLIST_DISABLE_TIME 300
#define ACE_WIFI_EVENTMGR_ENABLE
#define ACE_NETWORK_WATCHDOG_TIMEOUT 900000
#define ACE_NETWORK_WATCHDOG_BACKOFF_PERIOD 1800000
#define ACE_NETWORK_WATCHDOG_MAX_RESET_ATTEMPTS 3
#define ACE_BT_BLE_SUPPORT
#define ACE_BT_LITE_SUPPORT
#define ACE_BT_BLE_DEVICE_APPEARANCE 0
#define ACE_BT_BLE_CONNECTION_INTERVAL_CRITICAL_MIN 6
#define ACE_BT_BLE_CONNECTION_INTERVAL_CRITICAL_MAX 8
#define ACE_BT_BLE_CONNECTION_INTERVAL_HIGH_MIN 12
#define ACE_BT_BLE_CONNECTION_INTERVAL_HIGH_MAX 16
#define ACE_BT_BLE_CONNECTION_INTERVAL_BALANCED_MIN 80
#define ACE_BT_BLE_CONNECTION_INTERVAL_BALANCED_MAX 100
#define ACE_BT_BLE_CONNECTION_INTERVAL_LOW_MIN 400
#define ACE_BT_BLE_CONNECTION_INTERVAL_LOW_MAX 400
#define ACE_BT_BLE_CONNECTION_PRIORITY_CRITICAL_TIMEOUT 2000
#define ACE_BT_BLE_CONNECTION_PRIORITY_HIGH_TIMEOUT 2000
#define ACE_BT_BLE_CONNECTION_PRIORITY_BALANCED_TIMEOUT 2000
#define ACE_BT_BLE_CONNECTION_PRIORITY_LOW_TIMEOUT 2000
#define ACE_BT_BLE_CONNECTION_PRIORITY_CRITICAL_LATENCY 0
#define ACE_BT_BLE_CONNECTION_PRIORITY_HIGH_LATENCY 0
#define ACE_BT_BLE_CONNECTION_PRIORITY_BALANCED_LATENCY 0
#define ACE_BT_BLE_CONNECTION_PRIORITY_LOW_LATENCY 2
#define ACE_BT_BLE_CONNECTION_INTERVAL_ULTRA_LOW_MIN 1600
#define ACE_BT_BLE_CONNECTION_INTERVAL_ULTRA_LOW_MAX 1600
#define ACE_BT_BLE_CONNECTION_PRIORITY_ULTRA_LOW_TIMEOUT 2000
#define ACE_BT_BLE_CONNECTION_PRIORITY_ULTRA_LOW_LATENCY 0
#define ACE_BT_BEACON_ULTRA_LOW_LATENCY_INTERVAL 20
#define ACE_BT_BEACON_LOW_LATENCY_INTERVAL 100
#define ACE_BT_BEACON_BALANCED_INTERVAL 250
#define ACE_BT_BEACON_LOW_POWER_INTERVAL 1000
#define ACE_BT_BEACON_MAX_FILTERS 3
#define ACE_BT_MAX_CONNECTED_DEVICE_COUNT 8
#define ACE_BT_MAX_BONDED_DEVICE_COUNT 32
#define ACE_BT_UID 0
#define ACE_CONNECTIVITY_MANAGER
#define SS_POLICY_NAME "small"
#define ACM_SOCKS5_ENDPOINT ""
#define ACM_SVC_STACK_SIZE 5632
#define ACM_SSL_NUM 1
#define ACM_NO_V1
#define ACE_EVENTMGR_NUM_SUBSCRIBERS 20
#define ACE_EVENTMGR_PUBLISH_MSG_COUNT 10
#define ACE_EVENTMGR_NUM_APP_MODULES 4
#define ACE_EVENTMGR_MAX_PUBLISH_DATA_SIZE 256
#define ACE_EVENTMGR_DEMO_THREAD_STACK_SIZE 2048
#define ACE_EVENTMGR_DEMO_THREAD_PRIORITY 5
#define ACE_FACTORYRESET_DEREGISTER_TIMEOUT 0
#define ACS_HAL_WIFI_TEST_COEX
#define ACS_HAL_WIFI_TEST_ENABLE_NETWORKS
#define ACE_HAL_BT_TEST_LEVEL 0
#define ACE_HAL_BT_TEST_TS_AFQP
#define ACE_HAL_BT_TEST_TS_INTEGRATION
#define ACE_HAL_BT_TEST_TS_STRESS
#define ACE_HAL_BT_TEST_TS_KPI
#define ACE_HAL_BT_TEST_TS_STACK_INIT
#define ACE_HAL_BT_TEST_CLI
#define ACE_KVS_DS_DEFAULT_GROUP "kvsDefault"
#define WEB_SOCKETS_VERSION 4
#define LIBWEBSOCKETS_WITHOUT_H2
#define LIBWEBSOCKETS_WITHOUT_MQTT
#define SS_ENABLE_STATIC_POLICY
#define NANOPB_FIELD_WIDTH 8
#define ACE_API_TEST_FILES
#define OSAL_DEFAULT_LOG_LEVEL 1
#define ACE_API_TEST_FILE_NAME "/tmp/test.txt"
#define BuildType "OSAL_FREERTOS"
#define OSAL_FREERTOS
#define PriorityModel "PRIORITY_OTHER"
#define PRIORITY_OTHER
#define ACE_ALLOC_NETWORK_BUFFER_IS_MP
#define ACE_ALLOC_NETWORK_BUFFER_SIZE 7168
#define ACE_OSAL_THREADS_STACK_MIN 0
#define ACE_OSAL_THREADS_TLS_INDEX 0
#define TLSCONFIG

#endif /* ACE_CONFIG_H */
