/*
* Copyright 2020 NXP.
* This software is owned or controlled by NXP and may only be used strictly in accordance with the
* license terms that accompany it. By expressly accepting such terms or by downloading, installing,
* activating and/or otherwise using the software, you are agreeing that you have read, and that you
* agree to comply with and are bound by, such license terms. If you do not agree to be bound by the
* applicable license terms, then you may not retain, install, activate or otherwise use the software.
*/

/***********************************************************************************************************************
* This file was generated by the NXP AVS Smart Home Conversion Tool. Any manual edits made to this file
* will be overwritten if the respective MCUXpresso Build option is used
**********************************************************************************************************************/

/** @file discovery_endpoint_gen.h
 */

#ifndef _DISCOVERY_ENDPOINT_GEN_H_
#define _DISCOVERY_ENDPOINT_GEN_H_

#if defined(__cplusplus)
extern "C" {
#endif

/*******************************************************************************
* Includes
******************************************************************************/

#include "cJSON.h"

/*******************************************************************************
* Definitions
******************************************************************************/
extern const char avs_smart_home_json_string[];

/*******************************************************************************
* Public Functions
******************************************************************************/
#if defined(__cplusplus)
}
#endif

#endif /* _DISCOVERY_ENDPOINT_GEN_H_ */
