################################################################################
# Automatically-generated file. Do not edit!
################################################################################

OBJ_SRCS := 
S_SRCS := 
ASM_SRCS := 
C_SRCS := 
S_UPPER_SRCS := 
O_SRCS := 
EXECUTABLES := 
OBJS := 
C_DEPS := 

# Every subdirectory with source files must be described here
SUBDIRS := \
amazon_acs/ace/sdk/external/ceedling/ceedling_upstream/vendor/unity/src \
amazon_acs/dpk_impl/rt106a/common/afw/ace_hal \
amazon_acs/dpk_impl/rt106a/common/afw/ace_hal/cli/src \
amazon_acs/dpk_impl/rt106a/common/afw/ace_hal/device_info/src \
amazon_acs/dpk_impl/rt106a/common/afw/ace_hal/dha/src \
amazon_acs/dpk_impl/rt106a/common/afw/ace_hal/dha/src/crypto_utils \
amazon_acs/dpk_impl/rt106a/common/afw/ace_hal/dha/src/port \
amazon_acs/dpk_impl/rt106a/common/afw/ace_hal/factory_reset/src \
amazon_acs/dpk_impl/rt106a/common/afw/ace_hal/kvs/src \
amazon_acs/dpk_impl/rt106a/common/afw/ace_hal/log \
amazon_acs/dpk_impl/rt106a/common/afw/ace_hal/wifi/src \
amazon_acs/dpk_impl/rt106a/common/afw/common/src \
amazon_acs/dpk_impl/rt106a/common/asd/asd_cli \
amazon_acs/dpk_impl/rt106a/common/asd/asd_system_tools \
amazon_acs/dpk_impl/rt106a/common/asd/asd_utils \
amazon_acs/dpk_impl/rt106a/common/asd_logger \
amazon_acs/dpk_impl/rt106a/common/debug \
amazon_acs/dpk_impl/rt106a/common/utilities \
amazon_acs/dpk_impl/rt106a/external/Unity/extras/fixture/src \
amazon_acs/dpk_impl/rt106a/hal_impl \
amazon_acs/dpk_impl/rt106a/test/iot_tests \
board \
codec \
component/i2c \
component/lists \
component/osa \
component/serial_manager \
component/serial_manager/usb_cdc_adapter \
component/uart \
device \
drivers \
drivers/freertos \
freertos/demos/dev_mode_key_provisioning/src \
freertos/demos/network_manager \
freertos/freertos_kernel \
freertos/freertos_kernel/portable/GCC/ARM_CM4F \
freertos/freertos_kernel/portable/MemMang \
freertos/libraries/3rdparty/mbedtls/utils \
freertos/libraries/abstractions/platform/freertos \
freertos/libraries/c_sdk/aws/shadow/src \
freertos/libraries/c_sdk/standard/common \
freertos/libraries/c_sdk/standard/common/logging \
freertos/libraries/c_sdk/standard/common/taskpool \
freertos/libraries/c_sdk/standard/mqtt/src \
freertos/libraries/c_sdk/standard/serializer/src \
freertos/libraries/c_sdk/standard/serializer/src/json \
freertos/libraries/freertos_plus/standard/crypto/src \
freertos/libraries/freertos_plus/standard/pkcs11/src \
freertos/libraries/freertos_plus/standard/tls/src \
freertos/libraries/freertos_plus/standard/utils/src \
freertos/vendors/nxp/secure_sockets/lwip \
lwip/port \
lwip/src/api \
lwip/src/apps/sntp \
lwip/src/core \
lwip/src/core/ipv4 \
lwip/src/core/ipv6 \
lwip/src/netif \
lwip/src/netif/ppp \
mbedtls/amz_patch \
mbedtls/library \
mbedtls/port/ksdk \
py_crc \
sdmmc/host \
sdmmc/osa \
sdmmc/src \
source \
source/ble \
startup \
usb/device/class/cdc \
usb/device/class \
usb/device/source/ehci \
usb/device/source \
usb/phy \
utilities \
wiced/43xxx_BLE/wiced_bt/imxrt_port \
wiced/43xxx_Wi-Fi/WICED/RTOS/FreeRTOS/WWD \
wiced/43xxx_Wi-Fi/WICED/WWD/internal/bus_protocols/SDIO \
wiced/43xxx_Wi-Fi/WICED/WWD/internal/bus_protocols \
wiced/43xxx_Wi-Fi/WICED/WWD/internal/chips/4343W \
wiced/43xxx_Wi-Fi/WICED/WWD/internal \
wiced/43xxx_Wi-Fi/WICED/internal \
wiced/43xxx_Wi-Fi/WICED/network/LwIP/WWD \
wiced/43xxx_Wi-Fi/WICED/platform/MCU/LPC/WWD \
wiced/43xxx_Wi-Fi/WICED/platform/MCU \
xip \

