/*
 * Copyright 2021 Amazon.com, Inc. or its affiliates. All rights reserved.
 *
 * AMAZON PROPRIETARY/CONFIDENTIAL
 *
 * You may not use this file except in compliance with the terms and
 * conditions set forth in the accompanying LICENSE.TXT file. This file is a
 * Modifiable File, as defined in the accompanying LICENSE.TXT file.
 *
 * THESE MATERIALS ARE PROVIDED ON AN "AS IS" BASIS. AMAZON SPECIFICALLY
 * DISCLAIMS, WITH RESPECT TO THESE MATERIALS, ALL WARRANTIES, EXPRESS,
 * IMPLIED, OR STATUTORY, INCLUDING THE IMPLIED WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE, AND NON-INFRINGEMENT.
 */


/*-------------------------------------\
|                                      |
| this file is automatically generated |
|            do not modify             |
|                                      |
\_____________________________________*/

#ifndef _ACE_MAIN_H_
#define _ACE_MAIN_H_

#include <ace/ace.h>
#include <ace/ace_status.h>
#include <ace/dispatcher_core.h>

// The functions ace_main() and ace_mainWithConfig() that were previously
// prototyped here are now included in ace.h for ease of documentation.

/*
 * For ADVANCED DISPATCHER USERS only - 
 *
 * Use <disp_name>_disp_get_config() to get dispatcher config handle.
 * The handle can be used for registering new modules on the dispatcher.
 */
/* Dispatcher functions */
void Disp1_disp_start(void);
void Disp1_disp_stop(void);
ace_status_t Disp1_disp_get_config(aceDispatcher_config_t **d);

#endif /* _ACE_MAIN_H_ */
